## Unidade 01 - Avaliação 01

- **Aluno**: --preencher o nome completo--
- **Matrícula**: --preencer com a matrícula--

<br>
<div class="alert alert-info">
<b>Avisos.</b>
</div>


1. O notebook deverá ser renomeado para o nome completo do aluno seguindo o formato: Ivanovitch_Medeiros_Dantas_da_Silva.ipynb
2. Todas as questões devem ser respondidas através de códigos escritos em linguagem Python e no espaço destinado para esse fim. Criem células Markdown para destacar quando inicia e termina as questões. 
3. O notebook resultante deverá ser enviado através do Sigaa conforme tarefa cadastrada pelo professor. Ressalta-se que após o horário de final da aula, a submissão da tarefa estará fechada no Sigaa. 
4. O arquivo da base de dados não deve ser alterado.

## Base de dados

Nessa avaliação será utilizado a base de dados referente ao desempenho dos alunos do Instituto Metropole Digital em disciplinas do núcleo comum do curso de Bacharelado em Tecnologia da Informação. As informações sobre os alunos e disciplinas estão codificadas a fim de manter o anonimato e privacidade dos dados. 

A base de dados está em formato de planilha em excel. Para carregar esse arquivo em formato de **dataframe** utilizar o código abaixo: 

>```python
# Importar as bibliotecas necessárias
import pandas as pd
# Atribuir o nome da planilha para a variável "arquivo"
arquivo = 'imd_notas.xlsx'
# Carregar a base de dados para um objeto pandas.io.excel.ExcelFile
excel = pd.ExcelFile(arquivo)
# Imprimir o nome das planilhas
print(excel.sheet_names)
# Carregar a planilha excel para um objeto dataframe
dados = excel.parse(0)
# Imprimir as cinco primeiras linhas do dataframe
dados.head()
```

## a) (2.0 pontos) Investigando a base de dados

1. (0.2 pontos) Quais as colunas da base de dados?
2. (0.5 pontos)Quais colunas apresentam valores nulos (faltantes)? Em caso afirmativo, quantas linhas de cada coluna apresentam valores nulos?
3. (0.5 pontos) Quantos CEPs diferentes estão presentes na base de dados?
4. (0.4 pontos) Quantos alunos foram registrados?
5. (0.2 pontos) Qual o período em anos dos registros presentes na base de dados?
6. (0.2 ponto) Quantas disciplinas foram analisadas?

In [2]:
import pandas as pd
arquivo = 'imd_notas.xlsx'
excel = pd.ExcelFile(arquivo)
data = excel.parse(0)

In [9]:
data.columns

Index(['a_ID', 'CEP', 'ano_ingresso', 'periodo_ingresso', 'status',
       'ano_disciplina', 'periodo_disciplina', 'nota', 'disciplina_ID',
       'status.disciplina', 'enen-nota'],
      dtype='object')

In [3]:
data.isnull().sum()

a_ID                    0
CEP                     0
ano_ingresso            0
periodo_ingresso        0
status                  0
ano_disciplina          0
periodo_disciplina      0
nota                    0
disciplina_ID           0
status.disciplina       0
enen-nota             289
dtype: int64

In [5]:
len(set(data.CEP))

627

In [11]:
len(set(data.a_ID))

900

In [32]:
print(data.ano_ingresso.min(), " a ",data.ano_ingresso.max())

2014  a  2016

In [34]:
len(set(data.disciplina_ID))

7

## b) (2.0 pontos) Investigando a localização dos alunos


1. (2.0 pontos) Listar a quantidade total de alunos presentes nos cinco CEPs com mais registros.

<dica - consultar as funções duplicated() e value_counts()

In [69]:
alunos = ~data.a_ID.duplicated()
data[alunos].pivot_table(index="CEP", values="a_ID", aggfunc="count").sort_values('a_ID', ascending=False)

          a_ID
CEP
0           84
59290000    19
59570000    17
59280000    12
59550000     9
59152600     6
59380000     6
59152820     6
59575000     6
59151250     5
59200000     5
59700000     5
59182000     4
59173000     4
59162000     4
59064500     4
59650000     4
59300000     4
59080115     3
59347000     3
59151400     3
59360000     3
59078170     3
59400000     3
59590000     3
59460000     3
59190000     3
59064902     3
59054560     3
59151903     2
...        ...
59078970     1
59080015     1
59080040     1
59080090     1
59080370     1
59080520     1
59082000     1
59082010     1
59082070     1
59082110     1
59082140     1
59078290     1
59078220     1
59078200     1
59076150     1
59075190     1
59075260     1
59075290     1
59075710     1
59075750     1
59075810     1
59076500     1
59078180     1
59076700     1
59076725     1
59078040     1
59078050     1
59078110     1
59078160     1
97050023     1

[627 rows x 1 columns]

## c) (6.0 pontos) Investigando o desempenho das disciplinas

1. (1 ponto) Calcular as notas médias para cada disciplina.
2. (1,5 pontos) Calcular as notas médias para cada disciplina agrupadas por ano.
3. (2,0 pontos) Calcular o número de alunos aprovados e reprovados por disciplina e agrupados por ano.
4. (1,5 pontos) Calcular a quantidade de alunos classificados de acordo com a coluna status da base de dados.

,a_ID,CEP,ano_ingresso,periodo_ingresso,status,ano_disciplina,periodo_disciplina,nota,disciplina_ID,status.disciplina,enen-nota
0,0,59015430,2014,1,CANCELADO,2014,2,2.6,0,Reprovado,618.0
1,0,59015430,2014,1,CANCELADO,2015,1,8.0,0,Aprovado,618.0
2,1,59073120,2014,1,CANCELADO,2014,2,0.1,0,Reprovado,615.0
3,2,59072580,2014,1,ATIVO,2014,2,6.1,0,Aprovado,600.0
4,3,59088150,2014,1,ATIVO,2014,1,3.0,0,Reprovado,673.0
5,3,59088150,2014,1,ATIVO,2014,2,7.2,0,Aprovado,673.0
6,4,59064245,2014,1,CANCELADO,2014,2,2.1,0,Reprovado,642.0
7,4,59064245,2014,1,CANCELADO,2015,1,2.3,0,Reprovado,642.0
8,5,59112430,2014,1,ATIVO,2014,2,8.9,0,Aprovado,581.0
9,6,59152780,2014,1,CANCELADO,2014,2,2.4,0,Reprovado,660.0
10,6,59152780,2014,1,CANCELADO,2015,1,1.2,0,Reprovado,660.0
11,6,59152780,2014,1,CANCELADO,2015,2,6.0,0,Aprovado,660.0
12,7,59020330,2014,1,ATIVO,2014,2,5.6,0,Aprovado,647.0
13,8,59151610,2014,1,ATIVO,2014,2,1.5,0,Reprovado,621.0
14,8,59151610,2014,1,ATIVO,2015,1,6.9,0,Aprovado,621.0
15,9,59145510,2014,1,CANCELADO,2014,2,0.8,0,Reprovado,663.0
16,9,59145510,2014,1,CANCELADO,2015,1,0.6,0,Reprovado,663.0
17,9,59145510,2014,1,CANCELADO,2015,2,4.3,0,Reprovado,663.0
18,10,59075260,2014,1,CANCELADO,2014,2,5.1,0,Aprovado,698.0
19,10,59075260,2014,1,CANCELADO,2015,1,3.0,0,Reprovado,698.0
20,11,59086620,2014,1,CANCELADO,2014,2,0.0,0,Reprovado,621.0
21,12,59547000,2014,1,ATIVO,2014,2,2.6,0,Reprovado,634.0
22,12,59547000,2014,1,ATIVO,2015,1,5.9,0,Aprovado,634.0
23,13,59082180,2014,1,CANCELADO,2014,2,1.6,0,Reprovado,667.0
24,13,59082180,2014,1,CANCELADO,2015,1,7.3,0,Aprovado,667.0
25,14,59150500,2014,1,ATIVO,2014,2,1.2,0,Reprovado,630.0
26,14,59150500,2014,1,ATIVO,2015,1,4.3,0,Reprovado,630.0
27,14,59150500,2014,1,ATIVO,2015,2,7.7,0,Aprovado,630.0
28,15,59151800,2014,1,ATIVO,2014,2,8.5,0,Aprovado,662.0
29,16,59810000,2014,1,ATIVO,2014,2,9.8,0,Aprovado,613.0
...,...,...,...,...,...,...,...,...,...,...,...
4812,639,59158150,2016,1,ATIVO,2016,2,5.9,6,Aprovado,627.0
4813,641,59145450,2016,1,CANCELADO,2016,2,2.1,6,Reprovado,616.0
4814,643,59153025,2016,1,CANCELADO,2016,2,3.5,6,Reprovado,645.0
4815,644,59080115,2016,1,ATIVO,2016,1,7.1,6,Aprovado,678.0
4816,645,59360000,2016,1,ATIVO,2016,2,8.5,6,Aprovado,689.0
4817,647,59290000,2016,1,ATIVO,2016,2,5.1,6,Aprovado,634.0
4818,648,5021000,2016,1,ATIVO,2016,2,1.4,6,Reprovado,649.0
4819,649,59088460,2016,1,ATIVO,2016,1,5.5,6,Aprovado,643.0
4820,650,59149403,2016,1,ATIVO,2016,2,7.9,6,Aprovado,626.0
4821,651,59014150,2016,1,TRANCADO,2016,1,0.5,6,Reprovado,681.0
4822,652,35700416,2016,1,ATIVO,2016,2,7.8,6,Aprovado,578.0
4823,653,59054375,2016,1,ATIVO,2016,2,1.4,6,Reprovado,653.0
4824,655,59150600,2016,1,ATIVO,2016,2,7.0,6,Aprovado,629.0
4825,656,59730000,2016,1,ATIVO,2016,2,6.7,6,Aprovado,671.0
4826,657,59020030,2016,1,ATIVO,2016,2,1.0,6,Reprovado,643.0
4827,659,59066120,2016,1,CANCELADO,2016,2,0.0,6,Reprovado,682.0
4828,660,59080115,2016,1,ATIVO,2016,2,7.3,6,Aprovado,654.0
4829,661,59152600,2016,1,ATIVO,2016,2,0.0,6,Reprovado,651.0
4830,662,59136160,2016,1,ATIVO,2016,2,6.8,6,Aprovado,666.0
4831,663,59074420,2016,1,ATIVO,2016,2,2.3,6,Reprovado,681.0
4832,664,59149150,2016,1,ATIVO,2016,2,7.4,6,Aprovado,613.0
4833,665,59133305,2016,1,ATIVO,2016,2,2.8,6,Reprovado,605.0
4834,666,59190000,2016,1,CANCELADO,2016,2,8.2,6,Aprovado,623.0
4835,667,59080100,2016,1,ATIVO,2016,2,0.3,6,Reprovado,593.0
4836,668,59071080,2016,1,ATIVO,2016,2,5.2,6,Aprovado,706.0
4837,669,59151550,2016,1,ATIVO,2016,2,1.8,6,Reprovado,667.0
4838,670,18150000,2016,1,ATIVO,2016,2,6.2,6,Aprovado,616.0
4839,856,59076700,2016,1,ATIVO,2016,2,9.6,6,Aprovado,759.0
4840,672,59031120,2016,1,ATIVO,2016,2,1.7,6,Reprovado,655.0
4841,870,59280000,2016,1,ATIVO,2016,2,0.0,6,Reprovado,620.0